package ir.ac.kntu.SynchronousTransmission;

/**
 * A non-mutable message generated by the initiator and can not be modified
 * within a round
 * @param initiator
 * @param content
 */
public record StMessage<T>(Node initiator, int messageNo, T content) {

    public static StMessage<Object> NULL_MESSAGE = new StMessage<>(Node.NULL_NODE, 0, null);

    public boolean isNull(){
        return messageNo == 0 || initiator.equals(Node.NULL_NODE);
    }
}

