package ir.ac.kntu.SynchronousTransmission;

/**
 * A non-mutable message generated by the initiator and can not be modified
 * within a round
 * @param initiator
 * @param content
 */
public record StMessage<T>(Node initiator, T content) {

}

